FROM nginx:1.27-alpine

RUN addgroup -S appuser && adduser -S appuser -G appuser

COPY nginx.dev.conf /etc/nginx/nginx.conf
COPY src/ /usr/share/nginx/html/

RUN chown -R appuser:appuser /usr/share/nginx/html \
    /var/cache/nginx \
    /var/log/nginx \
    /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown appuser:appuser /var/run/nginx.pid

USER 10001

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
